spring:
 application:
  name: ${SPRING_APPLICATION_NAME}
 datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    format_sql: true
  dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
 mail:
  host: ${SPRING_MAIL_HOST}
  port: ${SPRING_MAIL_PORT}
  username: ${SPRING_MAIL_USERNAME}
  password: ${SPRING_MAIL_PASSWORD}
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
 sql:
  init:
   platform: mysql
   mode: always
   data-locations: classpath:data.sql
jwt:
 secretKey: ${JWT_SECRET_KEY}
deploy:
 env: dev